# General parameters
random_seed: 13
n_jobs: 2
overwrite: True

# Model training parameters
downsampling: 10
trained_model_path: '/home/scratch/mgoswami/trained_models'
dataset_path: '/home/scratch/mgoswami/datasets/'
min_length: 256
verbose: True
training_size: 1
model_architectures: 'all'

# Model evaluation parameters
normalize: True
result_path: '/home/scratch/mgoswami/results/'
n_repeats: 2
n_neighbors: [4, 10, 16]
split: 'test'
synthetic_ranking_criterion: 'f1'
n_splits: 100
n_validation_splits: 5
n_neighbors: [2, 4, 6]
n_splits: 100
evaluation_metric: 'Best F-1'
sliding_window: None
metric: 'influence'
top_k: 3
use_all_ranks: False
top_kr: None


