name: tsadams
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn
  - tqdm
  - matplotlib
  - pandas
  - patool
  - setuptools
  - cvxopt
  - cvxpy
  - networkx
  - statsmodels
  # - ruptures
  # - python=3.9
  # - ipykernel
  # - ipywidgets
  # - nb_conda_kernels
