name: tsadams
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - setuptools=65.5.0
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - tqdm=4.64.1
  - matplotlib=3.6.2
  - pandas=1.5.2
  - patool=1.12
  - cvxopt=1.3.0
  - cvxpy=1.2.2
  - networkx=2.8.8
  - statsmodels=0.13.5
  # missing packages:
  - numpy=1.23.4
  - pytorch=2.1.0
  - requests=2.31.0
  - pyyaml=6.0.1
  # - ruptures
  # - ipykernel
  # - ipywidgets
  # - nb_conda_kernels
