# General parameters
random_seed: 13
n_jobs: 1
overwrite: False
verbose: True

# Model training parameters
downsampling: 10
trained_model_path: './trained_models' # '/home/scratch/mgoswami/trained_models/'
dataset_path: './datasets' # '/home/scratch/mgoswami/datasets/'
min_length: 256
training_size: 1
model_architectures: ['RM', 'NN']  # 'all'

# Model evaluation parameters
normalize: True
results_path: './results' # '/home/scratch/mgoswami/results/'
n_repeats: 2
split: 'test'
synthetic_ranking_criterion: 'f1'
n_splits: 100
n_validation_splits: 5
n_neighbors: [2, 4, 6]
evaluation_metric: 'Best F-1'
sliding_window: !!null
metric: 'influence'
top_k: 3
use_all_ranks: False
top_kr: !!null
